# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Capabilities
    url: /#services
    weight: 20
  - name: Minimum viable offering
    url: /#offer
    weight: 30
  - name: Process
    url: /#process
    weight: 40
